# ---------- BASE IMAGE ----------
FROM python:3.11-slim

# ---------- SETUP ENV ----------
WORKDIR /app
COPY . /app

# ---------- INSTALL DEPENDENCIES ----------
RUN pip install --no-cache-dir -r requirements.txt

# ---------- EXPOSE PORT ----------
EXPOSE 8000

# ---------- START SERVER ----------
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
